import Head from 'next/head'
import Image from 'next/image'
import LayoutA from '../components/layoutA'
import Nav from '../components/nav'
import Home from '../components/home'

export default function HomePage() {
  return (<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
      </Head>

      <Nav />
      
      <LayoutA>
        <Home />
      </LayoutA>
    </>)
}
